// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Secret   []byte `json:"secret"`
}

type UserRole struct {
	ID     int32 `json:"id"`
	RoleID int32 `json:"role_id"`
	UserID int32 `json:"user_id"`
}
