// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_queries.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
select username, password, secret
from users
where username = ?
`

type GetUserRow struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Secret   string `json:"secret"`
}

func (q *Queries) GetUser(ctx context.Context, username string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i GetUserRow
	err := row.Scan(&i.Username, &i.Password, &i.Secret)
	return i, err
}
